# Generated by Django 4.2.4 on 2024-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_subproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
