# Generated by Django 5.0.4 on 2024-04-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_coupons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
