# Generated by Django 5.0.4 on 2024-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_delete_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='image',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
