# Generated by Django 5.0.4 on 2024-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
