# Generated by Django 5.0.4 on 2024-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placeorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
